import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Tab } from '@headlessui/react'
import classNames from "classnames";

const tabs=[
  {
  key:'all',
  display:'All'
  },
  
  {
 key:'ocean',
 display:'Ocean'
  },
  {
    key:'forest',
    display:'Forest'
    },
]


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className=" flex flex-col h-full bg-[url('/photography-bg.jpeg')] bg-cover">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='flex justify-between items-center h-[98px] px-10'>
      <div className='text-transparent'>hm</div>
      <div className='text-red-300 text-bold text-3xl'>RIZU Photography</div>
      <button className='rounded-3xl bg-white text-stone-500 px-7 py-3'>Get in touch</button>
      </header>


      <main className='grow'>
        <div className='flex flex-col items-center h-full'>
      <Tab.Group>
      <Tab.List className="flex items-center gap-7">
      {tabs.map((tab) => (
                <Tab key={tab.key} className="p-4">
                  {({ selected }) => (
                    <span
                      className={classNames(
                        "uppercase text-lg",
                        selected ? "text-white" : "text-stone-600"
                      )}
                    >
                      {tab.display}
                    </span>
                  )}
                </Tab>
              ))}
    
      </Tab.List>
      <Tab.Panels className='h-full bg-stone-700 bg-opacity-80  max-w-[900px] w-full p-2 sm:p-4 my-5 rounded-3xl '>
        <Tab.Panel className=''>All photography</Tab.Panel>
        <Tab.Panel>oceans</Tab.Panel>
        <Tab.Panel>Forest</Tab.Panel>
      </Tab.Panels>
    </Tab.Group>
    </div>
      </main>




      
      <footer className='h-[69px] flex justify-center items-center'>
            <p>Some taste different</p>
      </footer>
      
    </div>
  )
}
