import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Tab } from '@headlessui/react'
import classNames from "classnames";
import Masonry from 'react-masonry-css'
import Link from 'next/link';
import bgImage from "../public/photography-bg.jpeg";


const tabs=[
  {
  key:'all',
  display:'All'
  },
  
  {
 key:'ocean',
 display:'Ocean'
  },
  {
    key:'forest',
    display:'Forest'
    },
]


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className="h-full  overflow-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Image
        priority
        className="fixed left-0 top-0 z-0"
        src={bgImage}
        alt="background-image"
        placeholder="blur"
      />
 <div className="fixed left-0 top-0 w-full h-full z-10 from-stone-900 bg-gradient-to-t"></div>







      <header className=' fixed bg-stone-900 top-0 w-full z-10  flex justify-between items-center h-[99px] px-6'>

      <div className='text-red-300  text-xl uppercase font-medium'>RIZU Photography</div>
      <Link
      href='#'
      className='rounded-3xl bg-white text-stone-500 px-7 py-3'
      > Get in touch
      </Link>
      </header>


      <main className='pt-[150px]'>
        <div className='flex flex-col items-center h-full'>
      <Tab.Group>
      <Tab.List className="flex items-center gap-7">
      {tabs.map((tab) => (
                <Tab key={tab.key} className="p-4">
                  {({ selected }) => (
                    <span
                      className={classNames(
                        "uppercase text-lg",
                        selected ? "text-white" : "text-stone-600"
                      )}
                    >
                      {tab.display}
                    </span>
                  )}
                </Tab>
              ))}
    
      </Tab.List>
      <Tab.Panels className='h-full bg-stone-700 bg-opacity-80  max-w-[900px] w-full p-2 sm:p-4 my-5 rounded-3xl '>
        <Tab.Panel>
          <Masonry breakpointCols={2} className='flex gap-4' columnClassName=''>
          
            <img src='/ocean-1.jpeg' alt='2' className='my-4' />
            <img src='/ocean-2.jpeg' alt='2' className='my-4' />
            <img src='/ocean-3.jpeg' alt='2' className='my-4' />
            <img src='/ocean-4.jpeg' alt='2' className='my-2'/>
            <img src='/ocean-2.jpeg' alt='2' className='my-2'
             />




          </Masonry>
        </Tab.Panel>
        <Tab.Panel>oceans</Tab.Panel>
        <Tab.Panel>Forest</Tab.Panel>
      </Tab.Panels>
    </Tab.Group>
    </div>
      </main>




      <footer className="relative h-[90px] flex justify-center items-center uppercase text-lg font-medium z-20">
        <p>Photography portfolio</p>
      </footer>
      
    </div>
  )
}
